name: acronym
version: 1.7.0.11

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - split == 0.2.3.5

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
