name: sum-of-multiples
version: 1.5.0.10

dependencies:
  - base

library:
  exposed-modules: SumOfMultiples
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - containers == 0.6.5.1
  
tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sum-of-multiples
      - hspec
